name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --verbose

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run fmt
        run: cargo fmt --all -- --check

  pre-commit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install pre-commit

      - name: Run pre-commit checks
        run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        run: cargo test --all --verbose

  audit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run cargo-audit (vulnerability check)
        run: cargo audit

      - name: Install cargo-deny
        run: cargo install cargo-deny

      - name: Check dependency licenses with cargo-deny
        run: cargo deny check licenses

      - name: Check dependency bans (duplicates, yanked, etc.) with cargo-deny
        run: cargo deny check bans

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run code coverage (tarpaulin)
        run: cargo tarpaulin --out Html

  doc:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build documentation
        run: cargo doc --no-deps --all

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install actionlint
        run: |
          curl -sSL https://github.com/rhysd/actionlint/releases/latest/download/actionlint-darwin-arm64.zip -o actionlint.zip || \
          curl -sSL https://github.com/rhysd/actionlint/releases/latest/download/actionlint-linux-amd64.zip -o actionlint.zip
          unzip actionlint.zip -d actionlint-bin
          sudo mv actionlint-bin/actionlint /usr/local/bin/actionlint
      - name: Lint GitHub Actions workflows
        run: actionlint

  minimal-versions:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Build with minimal versions
        run: cargo update -Z minimal-versions && cargo build

  release-dry-run:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-release
        run: cargo install cargo-release
      - name: Release dry-run (cargo publish)
        run: cargo publish --dry-run
      - name: Version bump and changelog generation (dry-run)
        run: cargo release version --dry-run
      - name: Generate changelog (conventional commits)
        run: |
          pip install git-changelog
          git-changelog --conventional --output CHANGELOG.md
